name: Phoenix Server Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show System Info
        run: |
          echo "=========================="
          echo " Phoenix Server Build"
          echo "=========================="
          uname -a
          lscpu
          free -h
          df -h
